[package]
name = "hellolib"
version = "0.1.0"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2.2"
#xi4win = {path="xi4win",version="0.1.1"}
clap = "2.32.0"
dirs = "1.0.4"
once_cell = "0.1.6"
failure = "0.1.3"
mbox = "0.5.0"
parking_lot =  "0.7.0"