[workspace]
members = [
    "benchbot",
    "interface",
    "tokenbot",
    "fullnode",
    "fullnode-config",
    "genesis",
    "keybot",
    "ledgerbot",
    "budget",
        "crypto",
        "timing",
        "tokenbot",
]